### ISSUE TITLE
Request to Add Kafka Trial Project To List

### ISSUE THREAD

**Issue by imkrishnaagrawal** [semantalytics/awesome-kafka#28]
Project Name: Kafka Trial

Repository: [Kafka Trial](https://github.com/imkrishnaagrawal/KafkaTrail)

Description:
Kafka Trial is open-source desktop application designed to simplify Kafka topic exploration. Kafka Trial provides a user-friendly interface for browsing Kafka topics and inspecting data within them.

**Comment by zacharywhitley** [comment]
Added.  Thanks for the link
